name: Playwright Tests & Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      id: tests
      run: npx playwright test
      continue-on-error: true
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    - name: Upload Playwright video
      if: always()
      id: upload-video
      uses: actions/upload-artifact@v4
      with:
        name: playwright-video
        path: test-results/**/*.webm
        if-no-files-found: ignore
    - name: Add Playwright video to summary
      if: ${{ always() && steps.upload-video.outputs.artifact-url }}
      run: echo "### Playwright Video\n[Download video](${{ steps.upload-video.outputs.artifact-url }})" >> $GITHUB_STEP_SUMMARY

    - name: Upload Playwright report as an artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7

    - name: Setup Pages
      if: always()
      uses: actions/configure-pages@v4

    - name: Upload report to GitHub Pages
      if: always()
      uses: actions/upload-pages-artifact@v3
      with:
        path: playwright-report/

    - name: Deploy to GitHub Pages
      if: always()
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Check test status
      if: steps.tests.outcome == 'failure'
      run: exit 1
